### ISSUE TITLE
エラーが発生する

### ISSUE THREAD

**Issue by adoringonion** [u-yas/pesumi-editor#2]
`npm run dev` を使ってアプリを起動しようとすると以下のエラーが発生して正しく起動できません

```
Unhandled Runtime Error
TypeError: fs.existsSync is not a function
```

レンダラープロセス側の`pages/index.tsx`内でfsモジュールを使用しているのが原因だと思われます。remoteモジュールを使ってレンダラープロセス側でも呼び出すことはできますが、これはElectron公式としてはdeprecatedらしいので、ファイル入出力に関する処理はメインプロセス側に実装して、ipc通信を使って呼び出すほうが良いと思います

**Comment by u-yas** [comment]
ご報告ありがとうございます！
